version: "3.9"
services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/src
    command: yarn start

  test:
    build:
      context: .
    volumes:
      - .:/src
    command: yarn test